'use client';

import { ShieldCheck, Vote, Users, ChevronRight, Scale, Gavel } from 'lucide-react';
import { cn } from '@/lib/utils';
import { useState } from 'react';
import { ProposalDetailsModal, SubmitProposalModal, DelegateSupportModal } from '@/components/dashboard/governance-modals';

const PROPOSALS = [
    { title: 'OIP-12: Expand Vanguard Protocol to Sui Mainnet', status: 'Voting', votes: '14.2M / 20M', ends: '2 days', category: 'Expansion' },
    { title: 'OIP-11: Upgrade Neural Core to Gemini 2.0', status: 'Passed', votes: '18.1M / 18M', ends: 'Ended', category: 'Tech' },
    { title: 'OIP-10: Adjust Staking Rewards for Level 20+ Agents', status: 'Rejected', votes: '4.2M / 10M', ends: 'Ended', category: 'Economics' },
];

const STATUS_BADGE: Record<string, string> = {
    Voting: 'text-[#58a6ff] bg-[#1f6feb1a] border border-[#1f6feb33]',
    Passed: 'text-[#3fb950] bg-[#3fb9501a] border border-[#3fb95033]',
    Rejected: 'text-[#f85149] bg-[#f851491a] border border-[#f8514933]',
};

export default function GovernancePage() {
    const [isSubmitModalOpen, setIsSubmitModalOpen] = useState(false);
    const [isDelegateModalOpen, setIsDelegateModalOpen] = useState(false);
    const [selectedProposal, setSelectedProposal] = useState<any | null>(null);

    return (
        <div className="flex flex-col gap-6">
            {/* Page Header */}
            <div className="flex justify-between items-center">
                <div>
                    <h1 className="text-2xl font-bold text-[#e6edf3]">Neural Council</h1>
                    <p className="text-sm text-[#8b949e] mt-1">Decentralized governance for the OneMind ecosystem.</p>
                </div>
                <button
                    onClick={() => setIsSubmitModalOpen(true)}
                    className="px-4 py-2.5 bg-[#238636] hover:bg-[#2ea043] text-white font-semibold text-sm rounded-lg transition-colors"
                >
                    Submit Proposal
                </button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-5">
                {/* Left: Voting Power */}
                <div className="lg:col-span-4 flex flex-col gap-5">
                    {/* Voting Weight Card */}
                    <div className="bg-[#161b22] border border-[#1f6feb33] rounded-xl p-5">
                        <div className="flex items-center gap-2 mb-4">
                            <Scale className="w-4 h-4 text-[#58a6ff]" />
                            <h3 className="text-sm font-semibold text-[#58a6ff]">Your Voting Weight</h3>
                        </div>
                        <div className="mb-1">
                            <span className="text-4xl font-bold text-[#e6edf3] tracking-tight">1,240.50</span>
                            <span className="text-sm font-mono text-[#8b949e] ml-2">vOM</span>
                        </div>
                        <p className="text-xs text-[#8b949e] leading-relaxed mb-5">
                            Generated by your agent squad level and staked OCT assets.
                        </p>
                        <div className="space-y-1.5">
                            <div className="flex justify-between items-center">
                                <span className="text-xs text-[#8b949e] font-medium">Council Participation</span>
                                <span className="text-xs font-semibold text-[#e6edf3]">82%</span>
                            </div>
                            <div className="h-1.5 w-full bg-[#21262d] rounded-full overflow-hidden">
                                <div className="h-full w-[82%] bg-[#58a6ff] rounded-full" style={{ transition: 'width 0.6s ease' }} />
                            </div>
                        </div>
                    </div>

                    {/* Delegate Card */}
                    <div className="bg-[#161b22] border border-[#21262d] rounded-xl p-5">
                        <h3 className="text-sm font-semibold text-[#e6edf3] mb-4">Delegate Support</h3>
                        <div
                            onClick={() => setIsDelegateModalOpen(true)}
                            className="flex items-center gap-3 p-3 bg-[#0d1117] border border-[#21262d] hover:border-[#30363d] rounded-lg cursor-pointer transition-colors"
                        >
                            <div className="w-9 h-9 rounded-lg bg-[#bc8cff1a] border border-[#bc8cff33] flex items-center justify-center flex-shrink-0">
                                <Users className="w-4 h-4 text-[#bc8cff]" />
                            </div>
                            <div className="flex-1 min-w-0">
                                <div className="text-sm font-semibold text-[#e6edf3]">OneMind Foundation</div>
                                <div className="text-xs text-[#8b949e] mt-0.5">4.2M Votes Represented</div>
                            </div>
                            <ChevronRight className="w-4 h-4 text-[#8b949e] flex-shrink-0" />
                        </div>
                    </div>
                </div>

                {/* Right: Proposals */}
                <div className="lg:col-span-8 flex flex-col gap-4">
                    <div className="flex items-center gap-2">
                        <Gavel className="w-4 h-4 text-[#8b949e]" />
                        <h2 className="text-sm font-semibold text-[#e6edf3]">Active Proposals</h2>
                        <span className="text-xs bg-[#21262d] text-[#8b949e] px-2 py-0.5 rounded-full font-medium ml-1">
                            {PROPOSALS.length}
                        </span>
                    </div>

                    {PROPOSALS.map((proposal) => (
                        <div
                            key={proposal.title}
                            className="bg-[#161b22] border border-[#21262d] hover:border-[#30363d] rounded-xl p-5 transition-colors"
                        >
                            <div className="flex flex-col md:flex-row md:items-center gap-4">
                                <div className="flex-1 min-w-0">
                                    <div className="flex items-center gap-2 mb-2 flex-wrap">
                                        <span className={cn('text-[11px] font-semibold px-2 py-0.5 rounded uppercase tracking-wider', STATUS_BADGE[proposal.status] ?? 'text-[#8b949e]')}>
                                            {proposal.status}
                                        </span>
                                        <span className="text-xs text-[#8b949e] font-medium">#{proposal.category}</span>
                                    </div>
                                    <h4 className="text-base font-semibold text-[#e6edf3] leading-tight mb-2">{proposal.title}</h4>
                                    <div className="flex items-center gap-4 text-xs text-[#8b949e]">
                                        <span className="flex items-center gap-1">
                                            <Vote className="w-3.5 h-3.5" /> {proposal.votes}
                                        </span>
                                        <span className="flex items-center gap-1">
                                            <ShieldCheck className="w-3.5 h-3.5" />
                                            {proposal.ends === 'Ended' ? 'Voting ended' : `Ends in ${proposal.ends}`}
                                        </span>
                                    </div>
                                </div>

                                <div className="flex items-center gap-2 flex-shrink-0">
                                    <button
                                        onClick={() => setSelectedProposal(proposal)}
                                        className="px-4 py-2 border border-[#30363d] text-[#c9d1d9] font-semibold text-xs rounded-lg hover:bg-[#21262d] transition-colors"
                                    >
                                        Details
                                    </button>
                                    {proposal.status === 'Voting' && (
                                        <button
                                            onClick={() => setSelectedProposal(proposal)}
                                            className="px-5 py-2 bg-[#1f6feb] hover:bg-[#388bfd] text-white font-bold text-xs rounded-lg transition-colors"
                                        >
                                            Vote
                                        </button>
                                    )}
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            {/* Modals */}
            <SubmitProposalModal
                isOpen={isSubmitModalOpen}
                onClose={() => setIsSubmitModalOpen(false)}
            />

            <DelegateSupportModal
                isOpen={isDelegateModalOpen}
                onClose={() => setIsDelegateModalOpen(false)}
            />

            <ProposalDetailsModal
                isOpen={selectedProposal !== null}
                onClose={() => setSelectedProposal(null)}
                proposal={selectedProposal}
            />
        </div>
    );
}
