'use client';

import { ShieldCheck, Vote, Users, MessageSquare, ChevronRight, Scale, Gavel, HandMetal } from 'lucide-react';
import { motion } from 'framer-motion';
import { cn } from '@/lib/utils';

const PROPOSALS = [
    { title: 'OIP-12: Expand Vanguard Protocol to Sui Mainnet', status: 'Voting', votes: '14.2M / 20M', ends: '2 days', category: 'Expansion' },
    { title: 'OIP-11: Upgrade Neural Core to Gemini 2.0', status: 'Passed', votes: '18.1M / 18M', ends: 'Ended', category: 'Tech' },
    { title: 'OIP-10: Adjust Staking Rewards for Level 20+ Agents', status: 'Rejected', votes: '4.2M / 10M', ends: 'Ended', category: 'Economics' },
];

export default function GovernancePage() {
    return (
        <div className="flex flex-col gap-8">
            <div className="flex justify-between items-end">
                <div>
                    <h1 className="text-4xl font-bold tracking-tighter mb-2">NEURAL <span className="text-cyan-400">COUNCIL</span></h1>
                    <p className="text-gray-500 text-sm">Decentralized governance for the OneMind autonomous ecosystem.</p>
                </div>

                <button className="px-6 py-3 bg-white text-black font-black text-xs rounded-xl hover:bg-cyan-400 transition-all uppercase tracking-widest">
                    Submit Proposal
                </button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
                {/* Voting Power Section */}
                <div className="lg:col-span-4 flex flex-col gap-8">
                    <div className="glass-card p-8 bg-gradient-to-br from-cyan-500/10 to-transparent border-cyan-500/20">
                        <div className="flex items-center gap-3 mb-6 text-cyan-400">
                            <Scale className="w-6 h-6" />
                            <h3 className="text-sm font-black uppercase tracking-[0.2em]">Your Voting Weight</h3>
                        </div>
                        <div className="text-5xl font-black text-white mb-2">1,240.50<span className="text-xs font-mono ml-2 text-gray-500">vOM</span></div>
                        <p className="text-xs text-gray-500 leading-relaxed mb-8">Generated by your Agent Squad level and staked OCT assets.</p>

                        <div className="space-y-4">
                            <div className="flex justify-between text-[10px] uppercase font-mono text-gray-400">
                                <span>Council Participation</span>
                                <span>82%</span>
                            </div>
                            <div className="h-1 w-full bg-white/5 rounded-full overflow-hidden">
                                <div className="h-full w-[82%] bg-cyan-400 shadow-[0_0_10px_rgba(0,242,255,0.5)]" />
                            </div>
                        </div>
                    </div>

                    <div className="glass-card p-8">
                        <h3 className="text-xs font-black uppercase tracking-[0.2em] text-gray-500 mb-6 underline decoration-cyan-500 underline-offset-8">Delegate Support</h3>
                        <div className="flex items-center gap-4 p-4 border border-white/5 rounded-2xl bg-white/[0.02] hover:bg-white/[0.04] transition-all cursor-pointer">
                            <div className="w-10 h-10 rounded-xl bg-purple-500/20 flex items-center justify-center">
                                <Users className="w-5 h-5 text-purple-400" />
                            </div>
                            <div className="flex-1">
                                <div className="text-xs font-bold">OneMind Foundation</div>
                                <div className="text-[10px] text-gray-500">4.2M Votes Represented</div>
                            </div>
                            <ChevronRight className="w-4 h-4 text-gray-600" />
                        </div>
                    </div>
                </div>

                {/* Active Proposals Panel */}
                <div className="lg:col-span-8 space-y-6">
                    <div className="flex items-center gap-2 mb-4">
                        <Gavel className="w-4 h-4 text-gray-500" />
                        <h2 className="text-xs font-black uppercase tracking-[0.2em] text-gray-300">Active Proposals</h2>
                    </div>

                    {PROPOSALS.map((proposal, i) => (
                        <motion.div
                            key={proposal.title}
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: i * 0.1 }}
                            className="glass-card p-6 flex flex-col md:flex-row items-center gap-8 group hover:border-cyan-500/30 transition-all border-white/5"
                        >
                            <div className="flex-1">
                                <div className="flex items-center gap-3 mb-2">
                                    <span className={cn(
                                        "text-[8px] font-black px-2 py-0.5 rounded uppercase tracking-widest",
                                        proposal.status === 'Voting' ? "bg-cyan-500 text-black" : "bg-white/5 text-gray-500"
                                    )}>{proposal.status}</span>
                                    <span className="text-[10px] text-gray-600 font-mono italic">#{proposal.category}</span>
                                </div>
                                <h4 className="text-lg font-bold group-hover:text-cyan-400 transition-colors leading-tight mb-2">{proposal.title}</h4>
                                <div className="flex items-center gap-6 text-[10px] text-gray-500 font-mono uppercase tracking-widest">
                                    <span className="flex items-center gap-1.5"><Vote className="w-3 h-3" /> {proposal.votes}</span>
                                    <span className="flex items-center gap-1.5"><ShieldCheck className="w-3 h-3" /> Ends in {proposal.ends}</span>
                                </div>
                            </div>

                            <div className="flex gap-2">
                                <button className="px-5 py-3 border border-white/5 text-[10px] font-black uppercase hover:bg-white/5 transition-all rounded-xl">Details</button>
                                {proposal.status === 'Voting' && (
                                    <button className="px-8 py-3 bg-cyan-500 text-black text-[10px] font-black uppercase hover:scale-105 active:scale-95 transition-all rounded-xl shadow-[0_0_15px_rgba(0,242,255,0.2)]">VOTE</button>
                                )}
                            </div>
                        </motion.div>
                    ))}
                </div>
            </div>
        </div>
    );
}
