'use client';

import { ShieldCheck, Vote, Users, ChevronRight, Scale, Gavel } from 'lucide-react';
import { cn } from '@/lib/utils';
import { useState } from 'react';
import { motion } from 'framer-motion';
import { ProposalDetailsModal, SubmitProposalModal, DelegateSupportModal } from '@/components/dashboard/governance-modals';
import { useToast } from '@/components/ui/toast-context';

import { useCurrentAccount } from '@mysten/dapp-kit';
import { useOneBalance } from '@/hooks/use-one-chain';

const PROPOSALS: Proposal[] = [
    { title: 'OIP-12: Expand Vanguard Protocol to OneChain Mainnet', status: 'Passed', votes: '14.2M / 20M', ends: 'Ended', category: 'Archive' },
    { title: 'OIP-11: Upgrade Neural Core to Gemini 2.0', status: 'Passed', votes: '18.1M / 18M', ends: 'Ended', category: 'Archive' },
    { title: 'OIP-10: Adjust Staking Rewards for Level 20+ Agents', status: 'Rejected', votes: '4.2M / 10M', ends: 'Ended', category: 'Archive' },
];

const STATUS_BADGE: Record<string, string> = {
    Voting: 'text-cyan-400 bg-cyan-400/10 border border-cyan-400/20',
    Passed: 'text-emerald-400 bg-emerald-400/10 border border-emerald-400/20',
    Rejected: 'text-rose-400 bg-rose-400/10 border border-rose-400/20',
};

interface Proposal {
    title: string;
    status: 'Voting' | 'Passed' | 'Rejected';
    votes: string;
    ends: string;
    category: string;
}

export default function GovernancePage() {
    const [isSubmitModalOpen, setIsSubmitModalOpen] = useState(false);
    const [isDelegateModalOpen, setIsDelegateModalOpen] = useState(false);
    const [selectedProposal, setSelectedProposal] = useState<Proposal | null>(null);

    const account = useCurrentAccount();
    const { balance } = useOneBalance(account?.address);
    const { showToast } = useToast();
    const votingWeight = (Number(balance) / 1e9).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });

    return (
        <div className="flex flex-col gap-10">
            {/* Page Header */}
            <div className="flex justify-between items-end pb-4 border-b border-white/5">
                <div>
                    <h1 className="text-5xl font-black tracking-tighter text-white mb-2">Neural Council</h1>
                    <p className="text-base text-white/60 font-medium tracking-tight">Decentralized governance for the OneMind ecosystem.</p>
                </div>
                <button
                    onClick={() => setIsSubmitModalOpen(true)}
                    className="px-8 py-3 bg-white text-black font-black text-sm rounded-full hover:bg-cyan-400 hover:scale-105 transition-all shadow-[0_20px_40px_rgba(255,255,255,0.1)]"
                >
                    Submit Proposal
                </button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
                {/* Left: Voting Power */}
                <div className="lg:col-span-4 flex flex-col gap-8">
                    {/* Voting Weight Card */}
                    <div className="glass-card p-8 relative overflow-hidden group">
                        <div className="absolute top-0 right-0 p-8 opacity-5 transition-opacity group-hover:opacity-10">
                            <Scale className="w-24 h-24" />
                        </div>
                        <div className="flex items-center gap-2 mb-6">
                            <div className="w-2 h-2 rounded-full bg-cyan-400 shadow-[0_0_10px_rgba(6,182,212,0.5)]" />
                            <h3 className="text-xs font-black text-cyan-400 uppercase tracking-[0.2em]">Your Voting Weight</h3>
                        </div>
                        <div className="mb-2">
                            <span className="text-5xl font-black text-white tracking-tighter">{votingWeight}</span>
                            <span className="text-sm font-mono text-white/60 ml-3">vONE</span>
                        </div>
                        <p className="text-sm text-white/60 font-medium leading-relaxed mb-8">
                            Generated by your agent squad level and staked ONE assets.
                        </p>
                        <div className="space-y-3">
                            <div className="flex justify-between items-end">
                                <span className="text-xs text-white/40 font-black uppercase tracking-widest">Participation</span>
                                <span className="text-lg font-black text-white tracking-tighter">0%</span>
                            </div>
                            <div className="h-1.5 w-full bg-white/5 rounded-full overflow-hidden">
                                <motion.div
                                    initial={{ width: 0 }}
                                    animate={{ width: '0%' }}
                                    transition={{ duration: 1, ease: [0.16, 1, 0.3, 1] }}
                                    className="h-full bg-cyan-400 rounded-full shadow-[0_0_15px_rgba(6,182,212,0.5)]"
                                />
                            </div>
                        </div>
                    </div>

                    {/* Delegate Card */}
                    <div className="glass-card p-8 group transition-all hover:bg-white/[0.04]">
                        <h3 className="text-xs font-black text-white/60 uppercase tracking-[0.2em] mb-6">Delegate Support</h3>
                        <div
                            onClick={() => setIsDelegateModalOpen(true)}
                            className="flex items-center gap-4 p-4 rounded-2xl bg-white/[0.03] border border-white/5 hover:border-cyan-400/30 cursor-pointer transition-all active:scale-[0.98]"
                        >
                            <div className="w-12 h-12 rounded-xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center flex-shrink-0">
                                <Users className="w-5 h-5 text-purple-400" />
                            </div>
                            <div className="flex-1 min-w-0">
                                <div className="text-base font-black text-white tracking-tighter">OneMind Foundation</div>
                                <div className="text-xs text-white/60 font-medium mt-0.5 tracking-tight">System Delegate</div>
                            </div>
                            <ChevronRight className="w-5 h-5 text-white/20 group-hover:text-cyan-400 transition-colors" />
                        </div>
                    </div>
                </div>

                {/* Right: Proposals */}
                <div className="lg:col-span-8 flex flex-col gap-6">
                    <div className="flex items-center gap-3 mb-2">
                        <Gavel className="w-4 h-4 text-white/40" />
                        <h2 className="text-sm font-black text-white uppercase tracking-[0.2em]">Historical Archive</h2>
                        <span className="text-[10px] bg-white/5 text-white/80 px-2.5 py-0.5 rounded-full font-black ml-2 border border-white/5">
                            {PROPOSALS.length}
                        </span>
                    </div>

                    {PROPOSALS.map((proposal) => (
                        <div
                            key={proposal.title}
                            className="glass-card p-8 group hover:bg-white/[0.04] cursor-pointer"
                        >
                            <div className="flex flex-col md:flex-row md:items-center gap-8">
                                <div className="flex-1 min-w-0">
                                    <div className="flex items-center gap-3 mb-4 flex-wrap">
                                        <span className={cn('text-[10px] font-black px-2.5 py-1 rounded-full uppercase tracking-widest border', STATUS_BADGE[proposal.status] ?? 'text-white/40')}>
                                            {proposal.status}
                                        </span>
                                        <span className="text-[10px] text-white/60 font-black uppercase tracking-widest">#{proposal.category}</span>
                                    </div>
                                    <h4 className="text-xl font-black text-white tracking-tighter mb-4 group-hover:text-cyan-400 transition-colors uppercase leading-snug">{proposal.title}</h4>
                                    <div className="flex items-center gap-6 text-xs text-white/60 font-medium tracking-tight">
                                        <span className="flex items-center gap-1.5 text-white/40">
                                            <Vote className="w-4 h-4 opacity-100" /> {proposal.votes}
                                        </span>
                                        <span className="flex items-center gap-1.5">
                                            <ShieldCheck className="w-4 h-4 opacity-40" />
                                            {proposal.ends === 'Ended' ? 'Voting ended' : `Ends in ${proposal.ends}`}
                                        </span>
                                    </div>
                                </div>

                                <div className="flex items-center gap-3 flex-shrink-0">
                                    <button
                                        onClick={() => setSelectedProposal(proposal)}
                                        className="px-6 py-2.5 border border-white/10 text-white font-black text-xs rounded-full hover:bg-white/10 transition-all uppercase tracking-widest"
                                    >
                                        Details
                                    </button>
                                    {proposal.status === 'Voting' && (
                                        <button
                                            onClick={() => setSelectedProposal(proposal)}
                                            className="px-8 py-2.5 bg-cyan-400 text-black font-black text-xs rounded-full hover:scale-105 transition-all shadow-[0_10px_20px_rgba(6,182,212,0.2)] uppercase tracking-widest"
                                        >
                                            Vote
                                        </button>
                                    )}
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            {/* Modals */}
            <SubmitProposalModal
                isOpen={isSubmitModalOpen}
                onClose={() => setIsSubmitModalOpen(false)}
            />

            <DelegateSupportModal
                isOpen={isDelegateModalOpen}
                onClose={() => setIsDelegateModalOpen(false)}
            />

            <ProposalDetailsModal
                isOpen={selectedProposal !== null}
                onClose={() => setSelectedProposal(null)}
                proposal={selectedProposal}
            />
        </div>
    );
}
